# Generated by Django 5.0.4 on 2024-04-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_event_options_event_place_event_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
